# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d531b3c650c03d7d252a1430ae7ab668937f6ac6405f4ce8ca2cc128a9acc9bfe345f40161bf06c9c2e26cb47fb25e2c27efe39008b51105d0738127391e61ca

test:
  secret_key_base: f34e6f89e978c82bc79289e823062be9fe7c741fe7fccfad2d65d7e136bba7e1925661e410bab99ba3340ce8ed61d8116db0d05ff4be9960472a21094e790b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
